require: 
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/FilePath:
  SpecSuffixOnly: true

Rails/UniqueValidationWithoutIndex:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false